// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-modal/Current.tsx": () => import("../components/mockups/login-modal/Current.tsx"),
  "./components/mockups/login-modal/DwellGrid.tsx": () => import("../components/mockups/login-modal/DwellGrid.tsx"),
  "./components/mockups/login-modal/VoiceFirst.tsx": () => import("../components/mockups/login-modal/VoiceFirst.tsx")
};
